final List<Map<String, dynamic>> JambDataone2024 = [
  {
    "id": "1",
    "name":
        "The stress experienced by a wire of diameter yπ m loaded by a weight y2 N is",
    "options": ["π Nm−2", "2π Nm−2", "4π Nm−2", "8π Nm−2"],
    "correctAnswer": "4π Nm−2"
  },
  {
    "id": "2",
    "name": "Under which conditions is work done",
    "options": [
      "A man supports a heavy load on his head with hands.",
      "A woman holds a pot of water",
      "A boy climbs onto a table",
      "A man pushes against a stationary petrol tanker"
    ],
    "correctAnswer": "A boy climbs onto a table"
  },
  {
    "id": "3",
    "name": "Rainbow is formed when sunlight undergoes",
    "options": ["reflection", "refraction", "dispersion", "diffraction"],
    "correctAnswer": "dispersion"
  },
  {
    "id": "4",
    "name": "Find the value of a capacitor with voltage 5V and 30C.",
    "options": ["7f", "6f", "15f", "0.17f"],
    "correctAnswer": "6f"
  },
  {
    "id": "5",
    "name": "When a bus is accelerating, it must be",
    "options": [
      "changing its speed",
      "changing its velocity",
      "changing its position",
      "changing its direction"
    ],
    "correctAnswer": "changing its velocity"
  },
  {
    "id": "6",
    "name": "The friction due to air mass can be reduced by",
    "options": ["streaming", "lubricating", "propeller", "polishing"],
    "correctAnswer": "streaming"
  },
  {
    "id": "7",
    "name":
        "Which of the following operates based on magnetic effect of electric current?",
    "options": ["electric heater", "photocell", "Dynamo", "Cold cathode"],
    "correctAnswer": "Dynamo"
  },
  {
    "id": "8",
    "name":
        "When a charged ebonite rod is brought near a charged glass rod, there will be",
    "options": ["attraction", "repulsion", "spark", "no force experienced"],
    "correctAnswer": "repulsion"
  },
  {
    "id": "9",
    "name":
        "Pilots uses aneroid barometer to know the height above sea level because",
    "options": [
      "Very accurate",
      "Small and convenient",
      "Heavy and huge",
      "Costly"
    ],
    "correctAnswer": "Small and convenient"
  },
  {
    "id": "10",
    "name":
        "A light ray passing from air into water at an angle of 30º from the normal in air would",
    "options": [
      "make an angle greater than 30º in water surface",
      "be completely absorbed by the water surface",
      "be completely reflected by the water surface",
      "make an angle less than 30º from the normal in water"
    ],
    "correctAnswer": "make an angle less than 30º from the normal in water"
  },
  {
    "id": "11",
    "name":
        "A solid cube of aluminum is 1.5cm on each edge. The density of aluminum is 2700kgm−1. Find the mass of the cube.",
    "options": ["7.5g", "9.1g", "12.0g", "15.0g"],
    "correctAnswer": "9.1g"
  },
  {
    "id": "12",
    "name":
        "5 X 10−3 kg of liquid at its boiling point is evaporated in 20s by the heat generated by a resistor of 2Ω when a current of 10A is used. The specific latent heat of vaporization of the liquid is",
    "options": [
      "8.0 x 104 Jkg−1",
      "8.0 x 105 Jkg−1",
      "8.0 x 106 Jkg−1",
      "8.0 x 107 Jkg−1"
    ],
    "correctAnswer": "8.0 x 105 Jkg−1"
  },
  {
    "id": "13",
    "name":
        "If the S.V.P of water vapour was 13.5mmHg at 33ºC and 7.3mmHg at 7ºC. Find the percentage relative of the air on a day when average air temperature was 33ºC and dew point was 7ºC.",
    "options": ["55%", "60%", "54%", "51%"],
    "correctAnswer": "54%"
  },
  {
    "id": "14",
    "name": "Electrolysis can be investigated using",
    "options": ["Voltmeter", "Ammeter", "Galvanometer", "Voltameter"],
    "correctAnswer": "Voltameter"
  },
  {
    "id": "15",
    "name":
        "A wheelbarrow inclined at 60º to the horizontal is pushed with a force of 150N. What is the horizontal component of the applied force",
    "options": ["130N", "75N", "60N", "50N"],
    "correctAnswer": "75N"
  },
  {
    "id": "16",
    "name": "In a solar panel, solar beam is concentrated by using",
    "options": [
      "Concave mirror",
      "Convex mirror",
      "Plane mirror",
      "Triangular mirror"
    ],
    "correctAnswer": "Concave mirror"
  },
  {
    "id": "17",
    "name": "A rectifier is a device that changes",
    "options": ["D.C to D.C", "D.C to A.C", "A.C to A.C", "A.C to D.C"],
    "correctAnswer": "A.C to D.C"
  },
  {
    "id": "18",
    "name": "The dimension of young's modulus, E is given by",
    "options": ["MLT−1", "MT−2", "ML−1 T−2", "M−1 T"],
    "correctAnswer": "ML−1 T−2"
  },
  {
    "id": "19",
    "name":
        "The moon's acceleration due to gravity is 1/6 of the earth's value. The weight of a bowling ball on the moon would be",
    "options": [
      "6 times its weight on the earth",
      "1/6 of its weight on the earth",
      "36 times its weight on the earth",
      "equal to its weight on the earth"
    ],
    "correctAnswer": "1/6 of its weight on the earth"
  },
  {
    "id": "20",
    "name":
        "If a sheet of an insulating material is inserted between the plates of an air capacitor, the capacitance will",
    "options": ["become zero", "decrease", "increase", "remain unchanged"],
    "correctAnswer": "increase"
  },
  {
    "id": "21",
    "name":
        "288KJ is conducted across two opposite faces of a 3m cube of temperature gradient 90ºCm−1 in 7200s. Calculate the thermal conductivity.",
    "options": [
      "4.9 x 10−2 Wm−1 k−1",
      "5.0 x 10−2 Wm−1 k−1",
      "5.2 x 10−2 Wm−1 k−1",
      "5.1 x 10−2 Wm−1 k−1"
    ],
    "correctAnswer": "5.0 x 10−2 Wm−1 k−1"
  },
  {
    "id": "22",
    "name":
        "A sonometer's fundamental note is 50Hz, what is the new frequency when the tension is four times the original?",
    "options": ["25Hz", "100Hz", "200Hz", "250Hz"],
    "correctAnswer": "100Hz"
  },
  {
    "id": "23",
    "name": "Which of the following is not a part of model rocket?",
    "options": [
      "The body tube",
      "The nose cones",
      "The fin",
      "Not recovery devices"
    ],
    "correctAnswer": "Not recovery devices"
  },
  {
    "id": "24",
    "name":
        "A thick glass tumbler cracks when boiling water is poured into it because",
    "options": [
      "The inside expands more rapidly than the outside",
      "The inside expands less rapidly than the outside",
      "The expansion is even",
      "It does not expand"
    ],
    "correctAnswer": "The inside expands more rapidly than the outside"
  },
  {
    "id": "25",
    "name":
        "How much joules of heat are given out when a piece of iron, of mass 60g and specific heat capacity 460JKg−1 K−1, cools from 75ºC to 35ºC",
    "options": ["1000J", "1050J", "1067J", "1104J"],
    "correctAnswer": "1104J"
  },
  {
    "id": "26",
    "name":
        "The energy of light of frequency 2.0 x 1015 Hz is (h = 6.63 x 10−34 Js)",
    "options": [
      "3.33 x 10−18 J",
      "1.33 x 10−18 J",
      "1.33 x 10−19 J",
      "3.33 x 10−19 J"
    ],
    "correctAnswer": "1.33 x 10−18 J"
  },
  {
    "id": "27",
    "name":
        "A mass of gas at 40mmHg is heated from 298k to 348k at constant volume. Calculate the pressure exerted by the gas.",
    "options": ["50.21mmHg", "46.71mmHg", "42.35mmHg", "35.12mmHg"],
    "correctAnswer": "46.71mmHg"
  },
  {
    "id": "28",
    "name":
        "The distance between two successive crests of a water wave is 0.25m. If a particle on the surface of the water makes four complete vertical oscillations in one second. Calculate the speed of the wave.",
    "options": ["4ms−1", "3ms−1", "2ms−1", "1ms−1"],
    "correctAnswer": "1ms−1"
  },
  {
    "id": "29",
    "name":
        "The thermometer whose thermometric property is change in volume with temperature is",
    "options": [
      "Resistance thermometer",
      "Thermocouple",
      "Bimetallic thermometer",
      "Liquid-in-glass thermometer"
    ],
    "correctAnswer": "Liquid-in-glass thermometer"
  },
  {
    "id": "30",
    "name":
        "In a series resonant circuit, the current flowing in the circuit is",
    "options": ["maximum", "minimum", "zero", "unaffected"],
    "correctAnswer": "maximum"
  },
  {
    "id": "31",
    "name":
        "If a body in linear motion changes from point P to Q, the motion is",
    "options": ["Translational", "Rotational", "Simple harmonic", "Circular"],
    "correctAnswer": "Translational"
  },
  {
    "id": "32",
    "name": "Which of these gas laws is equivalent to workdone",
    "options": [
      "Charle's law",
      "Pressure law",
      "Boyle's law",
      "Gay Lussac's law"
    ],
    "correctAnswer": "Boyle's law"
  },
  {
    "id": "33",
    "name":
        "The process of adding impurities to a semiconductor material to increase its conductivity is",
    "options": ["Rectification", "Emission", "Doping", "Stabilization"],
    "correctAnswer": "Doping"
  },
  {
    "id": "34",
    "name":
        "A load of 300N is to be lifted by a machine with a velocity ratio of 2 and an efficiency of 60%. What effort will be applied to lift the load?",
    "options": ["100N", "150N", "250N", "400N"],
    "correctAnswer": "250N"
  },
  {
    "id": "35",
    "name":
        "The average translational kinetic energy of gas molecules depends on",
    "options": [
      "Temperature only",
      "Number of moles and temperature",
      "Pressure and temperature",
      "Pressure only"
    ],
    "correctAnswer": "Temperature only"
  },
  {
    "id": "36",
    "name":
        "The fourth overtone of a closed pipes is 900Hz, its fundamental frequency is",
    "options": ["50Hz", "100Hz", "200Hz", "400Hz"],
    "correctAnswer": "200Hz"
  },
  {
    "id": "37",
    "name":
        "A cell of internal resistance of 2Ω supplies current through a resistor, X if the efficiency of the cell is 75%, find the value of X.",
    "options": ["2Ω", "4Ω", "6Ω", "8Ω"],
    "correctAnswer": "6Ω"
  },
  {
    "id": "38",
    "name":
        "In voltage measurement, the potentiometer is preferred to voltmeter because it",
    "options": [
      "has a wider range",
      "consumes negligible current",
      "is bulky",
      "responds faster than voltmeter"
    ],
    "correctAnswer": "consumes negligible current"
  },
  {
    "id": "39",
    "name": "Which of the following is the best as shaving mirror?",
    "options": [
      "Concave mirror",
      "Convex mirror",
      "plane mirror",
      "parabolic mirror"
    ],
    "correctAnswer": "Concave mirror"
  },
  {
    "id": "40",
    "name":
        "A refrigerator uses 150W. If it is kept on for 336 hours non-stop, what is the energy consumed in KWh?",
    "options": ["60.20KWh", "50.40KWh", "25.01KWh", "30.20KWh"],
    "correctAnswer": "50.40KWh"
  },
  {
    "id": "41",
    "name":
        "What is the inductance reactance of a coil of 7H when connected to a 50Hz a.c circuit?",
    "options": ["2200Ω", "2000Ω", "1200Ω", "1100Ω"],
    "correctAnswer": "2200Ω"
  },
  {
    "id": "42",
    "name":
        "If a charge ion goes through a combined electric field E and magnetic field B, the resultant emergent velocity of the ion is",
    "options": ["EB", "EB", "BE", "E-B"],
    "correctAnswer": "E-B"
  },
  {
    "id": "43",
    "name":
        "In electrolysis, when same quantity of electricity is passed through different electrolytes, mass of substances deposited is proportional to",
    "options": [
      "Molecular weight",
      "Chemical equivalent",
      "Atomic number",
      "Chemical equivalent per valency"
    ],
    "correctAnswer": "Chemical equivalent"
  },
  {
    "id": "44",
    "name":
        "If the rate of evaporation is y, and the rate of condensation is x, then, a vapour is saturated when",
    "options": ["x > y", "x", "x = y", "x ≤ y"],
    "correctAnswer": "x = y"
  },
  {
    "id": "45",
    "name": "The degree of precision of a vernier caliper is",
    "options": ["0.005cm", "0.01cm", "0.1cm", "1.0cm"],
    "correctAnswer": "0.01cm"
  },
  {
    "id": "46",
    "name":
        "According to kinetic theory of gases, the pressure exerted by the gas on the wall is equal",
    "options": [
      "change in momentum per unit volume",
      "rate of change of momentum imparted by the walls per second per unit area",
      "momentum imparted to the walls per unit area",
      "change in momentum imparted to the walls per unit area"
    ],
    "correctAnswer":
        "rate of change of momentum imparted by the walls per second per unit area"
  },
  {
    "id": "47",
    "name":
        "The property by which a material returns to its original shape after the removal of force is called",
    "options": ["Elasticity", "Ductility", "Malleability", "Plasticity"],
    "correctAnswer": "Elasticity"
  },
  {
    "id": "48",
    "name": "The energy in a moving car is an example of",
    "options": [
      "Mechanical energy",
      "Electrical energy",
      "Potential energy",
      "Kinetic energy"
    ],
    "correctAnswer": "Kinetic energy"
  },
  {
    "id": "49",
    "name":
        "A hydrometer of mass y kg and volume 2y x 10−5 m3 floats in a fluid with 20% of its volume above the fluid, what is the density of the fluid?",
    "options": [
      "6.22 x 104 kgm−3",
      "6.23 x 104 kgm−3",
      "6.24 x 104 kgm−3",
      "6.25 x 104 kgm−3"
    ],
    "correctAnswer": "6.25 x 104 kgm−3"
  },
  {
    "id": "50",
    "name": "Convert 60ºC to degree Fahrenheit",
    "options": ["111.150 F", "115.560 F", "132.230 F", "140.000 F"],
    "correctAnswer": "140.000 F"
  },
  {
    "id": "51",
    "name":
        "What is the least possible error encountered when taking measurement with a metre rule?",
    "options": ["1.1mm", "0.5mm", "0.2mm", "0.1mm"],
    "correctAnswer": "0.5mm"
  }
];
