final List<Map<String, dynamic>> JambDataone2024 = [
  {
    "id": "1",
    "name":
        "The stress experienced by a wire of diameter yπ m loaded by a weight y2 N is",
    "options": ["π Nm−2", "2π Nm−2", "4π Nm−2", "8π Nm−2"],
    "correctAnswer": "4π Nm−2"
  },
  {
    "id": "2",
    "name": "Under which conditions is work done",
    "options": [
      "A man supports a heavy load on his head with hands.",
      "A woman holds a pot of water",
      "A boy climbs onto a table",
      "A man pushes against a stationary petrol tanker"
    ],
    "correctAnswer": "A boy climbs onto a table"
  },
  {
    "id": "3",
    "name": "Rainbow is formed when sunlight undergoes",
    "options": ["reflection", "refraction", "dispersion", "diffraction"],
    "correctAnswer": "dispersion"
  },
  {
    "id": "4",
    "name": "Find the value of a capacitor with voltage 5V and 30C.",
    "options": ["7f", "6f", "15f", "0.17f"],
    "correctAnswer": "6f"
  },
  {
    "id": "5",
    "name": "When a bus is accelerating, it must be",
    "options": [
      "changing its speed",
      "changing its velocity",
      "changing its position",
      "changing its direction"
    ],
    "correctAnswer": "changing its velocity"
  },
  {
    "id": "6",
    "name": "The friction due to air mass can be reduced by",
    "options": ["streaming", "lubricating", "propeller", "polishing"],
    "correctAnswer": "streaming"
  },
  {
    "id": "7",
    "name":
        "Which of the following operates based on magnetic effect of electric current?",
    "options": ["electric heater", "photocell", "Dynamo", "Cold cathode"],
    "correctAnswer": "Dynamo"
  },
  {
    "id": "8",
    "name":
        "When a charged ebonite rod is brought near a charged glass rod, there will be",
    "options": ["attraction", "repulsion", "spark", "no force experienced"],
    "correctAnswer": "repulsion"
  },
  {
    "id": "9",
    "name":
        "Pilots uses aneroid barometer to know the height above sea level because",
    "options": [
      "Very accurate",
      "Small and convenient",
      "Heavy and huge",
      "Costly"
    ],
    "correctAnswer": "Small and convenient"
  },
  {
    "id": "10",
    "name":
        "A light ray passing from air into water at an angle of 30º from the normal in air would",
    "options": [
      "make an angle greater than 30º in water surface",
      "be completely absorbed by the water surface",
      "be completely reflected by the water surface",
      "make an angle less than 30º from the normal in water"
    ],
    "correctAnswer": "make an angle less than 30º from the normal in water"
  },
  {
    "id": "11",
    "name":
        "A solid cube of aluminum is 1.5cm on each edge. The density of aluminum is 2700kgm−1. Find the mass of the cube.",
    "options": ["7.5g", "9.1g", "12.0g", "15.0g"],
    "correctAnswer": "9.1g"
  },
  {
    "id": "12",
    "name":
        "5 X 10−3 kg of liquid at its boiling point is evaporated in 20s by the heat generated by a resistor of 2Ω when a current of 10A is used. The specific latent heat of vaporization of the liquid is",
    "options": [
      "8.0 x 104 Jkg−1",
      "8.0 x 105 Jkg−1",
      "8.0 x 106 Jkg−1",
      "8.0 x 107 Jkg−1"
    ],
    "correctAnswer": "8.0 x 105 Jkg−1"
  },
  {
    "id": "13",
    "name":
        "If the S.V.P of water vapour was 13.5mmHg at 33ºC and 7.3mmHg at 7ºC. Find the percentage relative of the air on a day when average air temperature was 33ºC and dew point was 7ºC.",
    "options": ["55%", "60%", "54%", "51%"],
    "correctAnswer": "54%"
  },
  {
    "id": "14",
    "name": "Electrolysis can be investigated using",
    "options": ["Voltmeter", "Ammeter", "Galvanometer", "Voltameter"],
    "correctAnswer": "Voltameter"
  },
  {
    "id": "15",
    "name":
        "A wheelbarrow inclined at 60º to the horizontal is pushed with a force of 150N. What is the horizontal component of the applied force",
    "options": ["130N", "75N", "60N", "50N"],
    "correctAnswer": "75N"
  },
  {
    "id": "16",
    "name": "In a solar panel, solar beam is concentrated by using",
    "options": [
      "Concave mirror",
      "Convex mirror",
      "Plane mirror",
      "Triangular mirror"
    ],
    "correctAnswer": "Concave mirror"
  },
  {
    "id": "17",
    "name": "A rectifier is a device that changes",
    "options": ["D.C to D.C", "D.C to A.C", "A.C to A.C", "A.C to D.C"],
    "correctAnswer": "A.C to D.C"
  },
  {
    "id": "18",
    "name": "The dimension of young's modulus, E is given by",
    "options": ["MLT−1", "MT−2", "ML−1 T−2", "M−1 T"],
    "correctAnswer": "ML−1 T−2"
  },
  {
    "id": "19",
    "name":
        "The moon's acceleration due to gravity is 1/6 of the earth's value. The weight of a bowling ball on the moon would be",
    "options": [
      "6 times its weight on the earth",
      "1/6 of its weight on the earth",
      "36 times its weight on the earth",
      "equal to its weight on the earth"
    ],
    "correctAnswer": "1/6 of its weight on the earth"
  },
  {
    "id": "20",
    "name":
        "If a sheet of an insulating material is inserted between the plates of an air capacitor, the capacitance will",
    "options": ["become zero", "decrease", "increase", "remain unchanged"],
    "correctAnswer": "increase"
  },
  {
    "id": "21",
    "name":
        "288KJ is conducted across two opposite faces of a 3m cube of temperature gradient 90ºCm−1 in 7200s. Calculate the thermal conductivity.",
    "options": [
      "4.9 x 10−2 Wm−1 k−1",
      "5.0 x 10−2 Wm−1 k−1",
      "5.2 x 10−2 Wm−1 k−1",
      "5.1 x 10−2 Wm−1 k−1"
    ],
    "correctAnswer": "5.0 x 10−2 Wm−1 k−1"
  },
  {
    "id": "22",
    "name":
        "A sonometer's fundamental note is 50Hz, what is the new frequency when the tension is four times the original?",
    "options": ["25Hz", "100Hz", "200Hz", "250Hz"],
    "correctAnswer": "100Hz"
  },
  {
    "id": "23",
    "name": "Which of the following is not a part of model rocket?",
    "options": [
      "The body tube",
      "The nose cones",
      "The fin",
      "Not recovery devices"
    ],
    "correctAnswer": "Not recovery devices"
  },
  {
    "id": "24",
    "name":
        "A thick glass tumbler cracks when boiling water is poured into it because",
    "options": [
      "The inside expands more rapidly than the outside",
      "The inside expands less rapidly than the outside",
      "The expansion is even",
      "It does not expand"
    ],
    "correctAnswer": "The inside expands more rapidly than the outside"
  },
  {
    "id": "25",
    "name":
        "How much joules of heat are given out when a piece of iron, of mass 60g and specific heat capacity 460JKg−1 K−1, cools from 75ºC to 35ºC",
    "options": ["1000J", "1050J", "1067J", "1104J"],
    "correctAnswer": "1104J"
  },
  {
    "id": "26",
    "name":
        "The energy of light of frequency 2.0 x 1015 Hz is (h = 6.63 x 10−34 Js)",
    "options": [
      "3.33 x 10−18 J",
      "1.33 x 10−18 J",
      "1.33 x 10−19 J",
      "3.33 x 10−19 J"
    ],
    "correctAnswer": "1.33 x 10−18 J"
  },
  {
    "id": "27",
    "name":
        "A mass of gas at 40mmHg is heated from 298k to 348k at constant volume. Calculate the pressure exerted by the gas.",
    "options": ["50.21mmHg", "46.71mmHg", "42.35mmHg", "35.12mmHg"],
    "correctAnswer": "46.71mmHg"
  },
  {
    "id": "28",
    "name":
        "The distance between two successive crests of a water wave is 0.25m. If a particle on the surface of the water makes four complete vertical oscillations in one second. Calculate the speed of the wave.",
    "options": ["4ms−1", "3ms−1", "2ms−1", "1ms−1"],
    "correctAnswer": "1ms−1"
  },
  {
    "id": "29",
    "name":
        "The thermometer whose thermometric property is change in volume with temperature is",
    "options": [
      "Resistance thermometer",
      "Thermocouple",
      "Bimetallic thermometer",
      "Liquid-in-glass thermometer"
    ],
    "correctAnswer": "Liquid-in-glass thermometer"
  },
  {
    "id": "30",
    "name":
        "In a series resonant circuit, the current flowing in the circuit is",
    "options": ["maximum", "minimum", "zero", "unaffected"],
    "correctAnswer": "maximum"
  },
  {
    "id": "31",
    "name":
        "If a body in linear motion changes from point P to Q, the motion is",
    "options": ["Translational", "Rotational", "Simple harmonic", "Circular"],
    "correctAnswer": "Translational"
  },
  {
    "id": "32",
    "name": "Which of these gas laws is equivalent to workdone",
    "options": [
      "Charle's law",
      "Pressure law",
      "Boyle's law",
      "Gay Lussac's law"
    ],
    "correctAnswer": "Boyle's law"
  },
  {
    "id": "33",
    "name":
        "The process of adding impurities to a semiconductor material to increase its conductivity is",
    "options": ["Rectification", "Emission", "Doping", "Stabilization"],
    "correctAnswer": "Doping"
  },
  {
    "id": "34",
    "name":
        "A load of 300N is to be lifted by a machine with a velocity ratio of 2 and an efficiency of 60%. What effort will be applied to lift the load?",
    "options": ["100N", "150N", "250N", "400N"],
    "correctAnswer": "250N"
  },
  {
    "id": "35",
    "name":
        "The average translational kinetic energy of gas molecules depends on",
    "options": [
      "Temperature only",
      "Number of moles and temperature",
      "Pressure and temperature",
      "Pressure only"
    ],
    "correctAnswer": "Temperature only"
  },
  {
    "id": "36",
    "name":
        "The fourth overtone of a closed pipes is 900Hz, its fundamental frequency is",
    "options": ["50Hz", "100Hz", "200Hz", "400Hz"],
    "correctAnswer": "200Hz"
  },
  {
    "id": "37",
    "name":
        "A cell of internal resistance of 2Ω supplies current through a resistor, X if the efficiency of the cell is 75%, find the value of X.",
    "options": ["2Ω", "4Ω", "6Ω", "8Ω"],
    "correctAnswer": "6Ω"
  },
  {
    "id": "38",
    "name":
        "In voltage measurement, the potentiometer is preferred to voltmeter because it",
    "options": [
      "has a wider range",
      "consumes negligible current",
      "is bulky",
      "responds faster than voltmeter"
    ],
    "correctAnswer": "consumes negligible current"
  },
  {
    "id": "39",
    "name": "Which of the following is the best as shaving mirror?",
    "options": [
      "Concave mirror",
      "Convex mirror",
      "plane mirror",
      "parabolic mirror"
    ],
    "correctAnswer": "Concave mirror"
  },
  {
    "id": "40",
    "name":
        "A refrigerator uses 150W. If it is kept on for 336 hours non-stop, what is the energy consumed in KWh?",
    "options": ["60.20KWh", "50.40KWh", "25.01KWh", "30.20KWh"],
    "correctAnswer": "50.40KWh"
  },
  {
    "id": "41",
    "name":
        "What is the inductance reactance of a coil of 7H when connected to a 50Hz a.c circuit?",
    "options": ["2200Ω", "2000Ω", "1200Ω", "1100Ω"],
    "correctAnswer": "2200Ω"
  },
  {
    "id": "42",
    "name":
        "If a charge ion goes through a combined electric field E and magnetic field B, the resultant emergent velocity of the ion is",
    "options": ["EB", "EB", "BE", "E-B"],
    "correctAnswer": "E-B"
  },
  {
    "id": "43",
    "name":
        "In electrolysis, when same quantity of electricity is passed through different electrolytes, mass of substances deposited is proportional to",
    "options": [
      "Molecular weight",
      "Chemical equivalent",
      "Atomic number",
      "Chemical equivalent per valency"
    ],
    "correctAnswer": "Chemical equivalent"
  },
  {
    "id": "44",
    "name":
        "If the rate of evaporation is y, and the rate of condensation is x, then, a vapour is saturated when",
    "options": ["x > y", "x", "x = y", "x ≤ y"],
    "correctAnswer": "x = y"
  },
  {
    "id": "45",
    "name": "The degree of precision of a vernier caliper is",
    "options": ["0.005cm", "0.01cm", "0.1cm", "1.0cm"],
    "correctAnswer": "0.01cm"
  },
  {
    "id": "46",
    "name":
        "According to kinetic theory of gases, the pressure exerted by the gas on the wall is equal",
    "options": [
      "change in momentum per unit volume",
      "rate of change of momentum imparted by the walls per second per unit area",
      "momentum imparted to the walls per unit area",
      "change in momentum imparted to the walls per unit area"
    ],
    "correctAnswer":
        "rate of change of momentum imparted by the walls per second per unit area"
  },
  {
    "id": "47",
    "name":
        "The property by which a material returns to its original shape after the removal of force is called",
    "options": ["Elasticity", "Ductility", "Malleability", "Plasticity"],
    "correctAnswer": "Elasticity"
  },
  {
    "id": "48",
    "name": "The energy in a moving car is an example of",
    "options": [
      "Mechanical energy",
      "Electrical energy",
      "Potential energy",
      "Kinetic energy"
    ],
    "correctAnswer": "Kinetic energy"
  },
  {
    "id": "49",
    "name":
        "A hydrometer of mass y kg and volume 2y x 10−5 m3 floats in a fluid with 20% of its volume above the fluid, what is the density of the fluid?",
    "options": [
      "6.22 x 104 kgm−3",
      "6.23 x 104 kgm−3",
      "6.24 x 104 kgm−3",
      "6.25 x 104 kgm−3"
    ],
    "correctAnswer": "6.25 x 104 kgm−3"
  },
  {
    "id": "50",
    "name": "Convert 60ºC to degree Fahrenheit",
    "options": ["111.150 F", "115.560 F", "132.230 F", "140.000 F"],
    "correctAnswer": "140.000 F"
  },
  {
    "id": "51",
    "name":
        "What is the least possible error encountered when taking measurement with a metre rule?",
    "options": ["1.1mm", "0.5mm", "0.2mm", "0.1mm"],
    "correctAnswer": "0.5mm"
  },
  {
    "id": "1",
    "name":
        "An object is placed 25cm in front of a convex mirror has its image formed 5cm behind the mirror. What is the focal length of the convex mirror?",
    "options": ["8.20cm", "6.25cm", "5.60cm", "4.50cm"],
    "correctAnswer": "6.25cm"
  },
  {
    "id": "2",
    "name":
        "In a Hare's apparatus, the height of water and a liquid X are 0.3m and 0.5m respectively. The relative density of X is?",
    "options": ["0.4", "0.6", "1.7", "2.0"],
    "correctAnswer": "0.6"
  },
  {
    "id": "3",
    "name":
        "The quantity of heat required to melt ice of 0.2 kg whose specific latent heat is 3.4 x 10^5 J/Kg is",
    "options": ["6.8 x 10^4 J", "8.6 x 10^4 J", "1.7 x 10^5 J", "1.7 x 10^6 J"],
    "correctAnswer": "6.8 x 10^4 J"
  },
  {
    "id": "4",
    "name":
        "Water is not suitable for use as a thermometric liquid because \nI. It wets glass \nII. It needs to be coloured \nIII. It has a low density",
    "options": [
      "I only",
      "I and II only",
      "I, II, and III only",
      "II and III only"
    ],
    "correctAnswer": "I, II, and III only"
  },
  {
    "id": "5",
    "name": "The power of a convex lens of focal length 20cm is",
    "options": ["0.05D", "0.50D", "5.00D", "50.00D"],
    "correctAnswer": "5.00D"
  },
  {
    "id": "6",
    "name":
        "The charge of magnitude 1.6 x 10^−19 C is placed in a uniform electric field of intensity 1200Vm−1. Calculate its acceleration, if the mass of the charge is 9.1 x 10^−31 kg",
    "options": [
      "2.11 x 10^14 ms−2",
      "2.11 x 10^13 ms−2",
      "1.20 x 10^14 ms−2",
      "1.20 x 10^13 ms−2"
    ],
    "correctAnswer": "2.11 x 10^14 ms−2"
  },
  {
    "id": "7",
    "name":
        "Calculate the power of an object which moves through a distance of 500cm in 1s on a frictionless surface by a horizontal force of 50N",
    "options": ["200W", "300W", "350W", "250W"],
    "correctAnswer": "250W"
  },
  {
    "id": "8",
    "name":
        "The defect of the eye lens which occurs when the ciliary muscles are weak is",
    "options": ["Spherical aberration", "Astigmatism", "Presbyopia", "Myopia"],
    "correctAnswer": "Presbyopia"
  },
  {
    "id": "9",
    "name":
        "An effort of 40N is applied on a machine to lift a mass of 60kg. Determine the mechanical advantage of the machine [ g = 10ms^2 ]",
    "options": ["2400", "240", "150", "15"],
    "correctAnswer": "15"
  },
  {
    "id": "10",
    "name": "The land and sea breeze is attributed to",
    "options": [
      "conduction and radiation",
      "conduction",
      "radiation",
      "convection"
    ],
    "correctAnswer": "convection"
  },
  {
    "id": "11",
    "name": "A practical application of total internal reflection is found in",
    "options": ["rainbow", "diverging lens", "converging lens", "fiber optics"],
    "correctAnswer": "fiber optics"
  },
  {
    "id": "12",
    "name":
        "Calculate the magnetic force on an electron in a magnetic field of flux density 10T, with a velocity of 3 x 10^7 m/s at 60º to the magnetic field (e = 1.6 x 10^−19 C)",
    "options": [
      "4.8 x 10^−11 N",
      "4.6 x 10^−12 N",
      "4.16 x 10^−11 N",
      "4.3 x 10^−11 N"
    ],
    "correctAnswer": "4.16 x 10^−11 N"
  },
  {
    "id": "13",
    "name":
        "Calculate the upthrust on a spherical ball of volume 4.2 x 10^−4 m^3 when totally immersed in a liquid of density 1028kgm^−3",
    "options": ["5.2N", "4.3N", "3.0N", "2.4N"],
    "correctAnswer": "4.3N"
  },
  {
    "id": "14",
    "name":
        "At a pressure of 10^5 Nm−2, a gas has a volume of 20m^3. Calculate the volume at 4 x 10^5 Nm−2 at constant temperature.",
    "options": ["2m^3", "3m^3", "4m^3", "5m^3"],
    "correctAnswer": "5m^3"
  },
  {
    "id": "15",
    "name":
        "A particular household utilizes three electrical appliances for six hours daily if the appliances are rated 80W, 100W, and 120W respectively. Calculate the electrical bills paid monthly if an average month is 31 days. [1kwh = #24.08k]",
    "options": ["₦ 2843.22k", "₦ 1950.22k", "₦ 1343.66k", "₦ 46.23k"],
    "correctAnswer": "₦ 2843.22k"
  },
  {
    "id": "16",
    "name": "Newton's law of cooling is valid only for a",
    "options": [
      "small temperature range",
      "large temperature range",
      "free flow range",
      "presence of heat source"
    ],
    "correctAnswer": "small temperature range"
  },
  {
    "id": "17",
    "name":
        "When thermal energy in a solid is increased, the change in state is called",
    "options": ["melting", "evaporation", "freezing", "condensation"],
    "correctAnswer": "melting"
  },
  {
    "id": "18",
    "name":
        "Which of the following happens when the hole of a pinhole camera is diminished? \nI. clear \nII. sharp \nIII. poor \nIV. dark",
    "options": ["I only", "II only", "I and II only", "III and IV only"],
    "correctAnswer": "I and II only"
  },
  {
    "id": "19",
    "name":
        "A blacksmith heated a metal whose cubic expansivity is 3.9 x 10^−6 K^−1. Calculate the area expansivity.",
    "options": [
      "3.9 x 10^−6 K^−1",
      "2.6 x 10^−6 K^−1",
      "1.3 x 10^−6 K^−1",
      "1.6 x 10^−6 K^−1"
    ],
    "correctAnswer": "2.6 x 10^−6 K^−1"
  },
  {
    "id": "20",
    "name": "The unit of impedance is",
    "options": ["Ω", "T", "H", "W"],
    "correctAnswer": "Ω"
  },
  {
    "id": "21",
    "name":
        "If the displacement of a car is proportional to the square of time, then the car is moving with",
    "options": [
      "Uniform acceleration",
      "Uniform velocity",
      "Increasing acceleration",
      "Decreasing acceleration"
    ],
    "correctAnswer": "Uniform acceleration"
  },
  {
    "id": "22",
    "name":
        "The force of attraction between molecules of the same substance is",
    "options": ["cohesion", "capillarity", "adhesion", "surface tension"],
    "correctAnswer": "cohesion"
  },
  {
    "id": "23",
    "name":
        "If the pressure on an enclosed gas is doubled and its temperature rises from 27ºC to 127ºC, then its volume will",
    "options": [
      "increase by 2/3",
      "increase by 1/3",
      "decrease by 2/3",
      "decrease by 1/3"
    ],
    "correctAnswer": "decrease by 2/3"
  },
  {
    "id": "24",
    "name":
        "The simple form of the lead acid accumulator often has a negative pole of",
    "options": [
      "Zinc peroxide",
      "Lead peroxide",
      "Sulphuric acid",
      "lead plate"
    ],
    "correctAnswer": "lead plate"
  },
  {
    "id": "25",
    "name": "A monochromatic light is one that",
    "options": [
      "can undergo dispersion",
      "cannot be refracted",
      "has one wavelength",
      "has many wavelengths"
    ],
    "correctAnswer": "has one wavelength"
  },
  {
    "id": "26",
    "name": "Bifocal lens is used to correct the eye defect of",
    "options": ["astigmatism", "hypermetropia", "myopia", "presbyopia"],
    "correctAnswer": "presbyopia"
  },
  {
    "id": "27",
    "name":
        "A force of 10N extends a spring of natural length 1m by 0.02m, calculate the length of the spring when the applied force is 40N.",
    "options": ["0.08m", "0.09m", "1.08m", "1.80m"],
    "correctAnswer": "1.08m"
  },
  {
    "id": "28",
    "name": "Infra-red thermometers work by detecting the",
    "options": [
      "radiation from the body and converting it to temperature",
      "conduction of heat from the body",
      "convective air pulse from the body",
      "absorption of heat by the body"
    ],
    "correctAnswer": "radiation from the body and converting it to temperature"
  },
  {
    "id": "29",
    "name":
        "The efficiency of a cell with internal resistance of 2Ω supplying current to a 6Ω resistor is",
    "options": ["25%", "50%", "65%", "75%"],
    "correctAnswer": "75%"
  },
  {
    "id": "30",
    "name":
        "Which of the following measuring instruments operates based on the heating effect of electric current?",
    "options": [
      "moving iron ammeter",
      "hot wire ammeter",
      "galvanometer",
      "electric heater"
    ],
    "correctAnswer": "hot wire ammeter"
  },
  {
    "id": "31",
    "name": "What is the colour of a red rose under a blue light?",
    "options": ["Green", "Blue", "Yellow", "Black"],
    "correctAnswer": "Black"
  },
  {
    "id": "32",
    "name":
        "Calculate the value of electric field intensity due to a charge of 4μC if the force due to the charge is 8N",
    "options": [
      "2.0 x 10^6 NC−1",
      "3.0 x 10^6 NC−1",
      "4.0 x 10^6 NC−1",
      "8.0 x 10^6 NC−1"
    ],
    "correctAnswer": "2.0 x 10^6 NC−1"
  },
  {
    "id": "33",
    "name":
        "An accumulator is 90% efficient. If it gives out 2700J of energy while discharging, how much energy does it take in?",
    "options": ["3600J", "3000J", "3200J", "2430J"],
    "correctAnswer": "3000J"
  },
  {
    "id": "34",
    "name":
        "Two capacitors of 0.0003μF and 0.0006μF are connected in series, find their combined capacitance.",
    "options": ["0.0009μF", "0.0002μF", "0.0005μF", "0.0001μF"],
    "correctAnswer": "0.0002μF"
  },
  {
    "id": "35",
    "name":
        "Two points on a velocity-time graph have coordinates (2s, 5m/s) and (4s, 15m/s). Calculate the mean acceleration",
    "options": ["5.0ms^2", "0.83ms^2", "1.5ms^2", "2.0ms^2"],
    "correctAnswer": "5.0ms^2"
  },
  {
    "id": "36",
    "name":
        "An air force jet flying with a speed of 335m/s went past an anti-aircraft gun. How far is the aircraft 5s later when the gun was fired?",
    "options": ["838m", "1675m", "670m", "3350m"],
    "correctAnswer": "1675m"
  },
  {
    "id": "37",
    "name": "The diaphragm in the camera is similar to what part of the eyes?",
    "options": ["Cornea", "Lens", "Ciliary muscle", "Iris"],
    "correctAnswer": "Iris"
  },
  {
    "id": "38",
    "name": "The device for measuring the angle of dip is",
    "options": ["Dip circle", "Dip inclination", "Dip variation", "Dip meter"],
    "correctAnswer": "Dip circle"
  },
  {
    "id": "39",
    "name":
        "The velocity ratio of an inclined plane at 60º to the horizontal is",
    "options": ["1.055", "1.155", "1.255", "2.00"],
    "correctAnswer": "1.155"
  },
  {
    "id": "40",
    "name":
        "The bursting of water pipes during very cold weather, when the water in the pipes form ice could be attributed to",
    "options": [
      "contraction of pipes when cooled",
      "expansion of water on freezing",
      "contraction of water on freezing",
      "expansion of ice on melting"
    ],
    "correctAnswer": "expansion of water on freezing"
  },
  {
    "id": "41",
    "name": "One of these is not the use of an electroscope",
    "options": [
      "testing the type of charge on a charge body",
      "measuring ionization current in air",
      "detecting the pressure of charge on a charged body",
      "producing electric charge in a body"
    ],
    "correctAnswer": "producing electric charge in a body"
  },
  {
    "id": "42",
    "name":
        "As per Faraday's laws of electromagnetic induction, an e.m.f is induced in a conductor whenever it",
    "options": [
      "lies parallel to the magnetic flux",
      "lies in a magnetic field",
      "lies outside but close to a magnetic field",
      "cuts magnetic flux"
    ],
    "correctAnswer": "cuts magnetic flux"
  },
  {
    "id": "43",
    "name": "Photometer is used to measure",
    "options": [
      "Kinetic energy of liberated electrons",
      "Intensity of light",
      "frequency of light",
      "wavelength of light"
    ],
    "correctAnswer": "Intensity of light"
  },
  {
    "id": "44",
    "name":
        "The acceleration of a free fall due to gravity is not a constant everywhere on the Earth's surface because of the",
    "options": [
      "mass of the earth",
      "elliptical shape of the earth",
      "variation in the density of the earth",
      "rotation of the earth about its axis"
    ],
    "correctAnswer": "elliptical shape of the earth"
  },
  {
    "id": "45",
    "name": "An example of a non-rechargeable cell is",
    "options": ["nickel iron", "mercury cadmium", "dry leclanche", "lead-acid"],
    "correctAnswer": "dry leclanche"
  },
  {
    "id": "46",
    "name": "The dimension of power is",
    "options": ["ML^2T^−3", "MLT^2", "ML^2T^−2", "MLT^2"],
    "correctAnswer": "ML^2T^−3"
  },
  {
    "id": "47",
    "name":
        "A boy standing 408m from a wall blew a trumpet and heard the echo 2.4s later. Calculate the speed of the sound",
    "options": ["310m/s", "320m/s", "330m/s", "340m/s"],
    "correctAnswer": "340m/s"
  },
  {
    "id": "2",
    "name":
        "Which of the following statements about the properties of the electric field produced by charged parallel plates is not correct?",
    "options": [
      "The electric field in the region outside the parallel plate is zero, except for the edge effects",
      "The magnitude of the electric field strength at any point between the plates, except near the edges, depends on the magnitude of the charge on each plate.",
      "The magnitude of the electric field strength at any point between the plates is directly proportional to the magnitude of the charge on each plate.",
      "The electric field is uniform everywhere in the space between the parallel plates"
    ],
    "correctAnswer":
        "The electric field is uniform everywhere in the space between the parallel plates"
  },
  {
    "id": "3",
    "name":
        "The process of producing electric current by a changing magnetic field is referred to as",
    "options": [
      "magnet induction",
      "electromagnetic induction",
      "flux linkage",
      "electrostatic induction"
    ],
    "correctAnswer": "electromagnetic induction"
  },
  {
    "id": "4",
    "name":
        "In a controlled thermal fission reactor, the use of control rods will not affect the",
    "options": [
      "energy generated in the nuclear reactor",
      "rate of production of the neutrons.",
      "speed of the neutrons released on fission.",
      "amount of radiation produced in the nuclear reactor."
    ],
    "correctAnswer": "energy generated in the nuclear reactor"
  },
  {
    "id": "5",
    "name":
        "A body starts with an initial velocity of 20 m/s and moves with a uniform acceleration, a, for 15 seconds. Which of the following equations represents the distance, S, traveled?",
    "options": ["300 + 56a2", "300 + 225a2", "300 + 2252a", "300a + 2252"],
    "correctAnswer": "300 + 225a2"
  },
  {
    "id": "6",
    "name":
        "In a mass spectrometer, an ion of charge, q, and mass, m, moving in a path of radius, r, in a field of flux density, B, has a speed of",
    "options": ["qBrm", "mrqB", "qmBr", "mqr"],
    "correctAnswer": "qmBr"
  },
  {
    "id": "7",
    "name": "Increasing the frequency of a sound wave produces a sound with",
    "options": [
      "higher pitch",
      "longer wavelength",
      "more overtones",
      "reduced loudness"
    ],
    "correctAnswer": "higher pitch"
  },
  {
    "id": "8",
    "name":
        "A planet has mass, M, and radius R, If the universal gravitational constant is G, what is the expression for the escape velocity of an object on the planet?",
    "options": ["GR√2", "2GM√R", "2G√R", "GM√R"],
    "correctAnswer": "2GM√R"
  },
  {
    "id": "9",
    "name": "An atom in an excited state is one whose",
    "options": [
      "electrons are in the conduction band.",
      "potential energy is minimum.",
      "potential energy is maximum.",
      "electrons have moved to a higher energy level."
    ],
    "correctAnswer": "electrons have moved to a higher energy level."
  },
  {
    "id": "10",
    "name":
        "The most appropriate value of fuse for a kettle rated 220 V, 1.06 kW is",
    "options": ["3A", "6A", "5A", "4A"],
    "correctAnswer": "5A"
  },
  {
    "id": "11",
    "name":
        "A 100 kg device is pulled up a plane inclined at 30° to the horizontal with a force of 1000 N. If the coefficient of friction between the device and the surface is 0.25, determine the total force opposing the motion. [ g = 10 ms-2]",
    "options": ["283.5N", "975.0N", "216.5N", "716.5N"],
    "correctAnswer": "975.0N"
  },
  {
    "id": "12",
    "name":
        "A solenoid is constructed by winding an insulated copper on a long test tube. A constant direct current is passed through the solenoid. Which of the following actions will not increase the strength of the magnetic field of the solenoid? Inserting a",
    "options": [
      "steel rod in the test tube",
      "Nickel rod in the test tube",
      "Brass rod in the test tube",
      "Soft iron rod in the test tube"
    ],
    "correctAnswer": "Brass rod in the test tube"
  },
  {
    "id": "13",
    "name":
        "The following statements are advantages of a solid dielectric material between the plates of a capacitor except that",
    "options": [
      "the maximum potential difference the capacitor can withstand is increased.",
      "it increases the electrical conduction of the capacitor.",
      "the capacitance of the capacitor of given dimensions is much greater than that of the plates in a vacuum.",
      "it keeps the plates at a fixed separation."
    ],
    "correctAnswer": "it increases the electrical conduction of the capacitor."
  },
  {
    "id": "14",
    "name":
        "Which of the following devices is used to compare the relative magnitudes of charges on two given bodies?",
    "options": [
      "Ebonite rod",
      "Proof Plane",
      "Gold Leaf Electroscope",
      "Electrophorus"
    ],
    "correctAnswer": "Gold Leaf Electroscope"
  },
  {
    "id": "15",
    "name": "The instrument used to measure relative humidity is a",
    "options": ["Hygrometer", "Barometer", "Hydrometer", "Manometer"],
    "correctAnswer": "Hygrometer"
  },
  {
    "id": "16",
    "name":
        "A ball of mass 0.8 kg is dropped from a height, H. Just before hitting the ground, its velocity is 5.0 m/s. Determine H. [g = 10 ms-2]",
    "options": ["1.25m", "4.00m", "6.25m", "1.60m"],
    "correctAnswer": "1.25m"
  },
  {
    "id": "17",
    "name":
        "The following statements are observations made about a towing vehicle and a bus that is being towed: I. The force exerted on the bus by the towing vehicle is of the same magnitude as the force that the bus exerts on the road. II. The force exerted on the bus by the towing vehicle is of the same magnitude as the force exerted on the towing vehicle by the bus. III. The towing vehicle exerts a force on the bus greater than the force exerted by the bus on the towing vehicle. IV. The towing vehicle exerts a force on the bus that is the same as the force the road exerts on the towing vehicle. Which of the following statements is/are correct?",
    "options": ["II, III and IV", "II only", "I, II and III only", "I only"],
    "correctAnswer": "II only"
  },
  {
    "id": "18",
    "name":
        "Which of the following statements about a ferromagnetic material is correct? It",
    "options": [
      "has a high susceptibility.",
      "attracts non-magnetic materials.",
      "has low relative permeability.",
      "repels other magnetic materials."
    ],
    "correctAnswer": "has a high susceptibility."
  },
  {
    "id": "19",
    "name":
        "The type of mirror used by dentists to inspect the teeth of patients is a",
    "options": [
      "Plane mirror",
      "cylindrical mirror",
      "concave mirror",
      "convex mirror"
    ],
    "correctAnswer": "concave mirror"
  },
  {
    "id": "20",
    "name":
        "In an RLC series circuit at resonance, the voltages across the resistor and the inductor are 30 V and 40 V respectively. Determine the voltage across the capacitor.",
    "options": ["50V", "30V", "70V", "40V"],
    "correctAnswer": "50V"
  },
  {
    "id": "21",
    "name":
        "A sound of frequency 512 Hz reaches a listener 100 m away. If the sound travels in air at s.t.p., what is its wavelength? [speed of sound in air = 331 m/s]",
    "options": ["1.550m", "0.646m", "5.120m", "0.195m"],
    "correctAnswer": "0.646m"
  },
  {
    "id": "22",
    "name":
        "A charge of 10 C is transferred across a potential difference of 220 V. Determine the work done.",
    "options": ["22J", "2200J", "210J", "230J"],
    "correctAnswer": "2200J"
  },
  {
    "id": "23",
    "name":
        "The ratio of maximum range to maximum height of a projectile is 4. Determine the angle of projection.",
    "options": ["30°", "60°", "45°", "0°"],
    "correctAnswer": "45°"
  },
  {
    "id": "24",
    "name":
        "The range of wavelengths of the infrared waves in an electromagnetic spectrum is 10−3 m to 10−6m. The wavelength of the radiation is",
    "options": [
      "longer than 10−6m.",
      "shorter than 10−6m.",
      "shorter than 103m.",
      "longer than 103m."
    ],
    "correctAnswer": "longer than 10−6m."
  },
  {
    "id": "25",
    "name":
        "An electron moves from an energy level of -8.6 eV to another level of -3.5 eV. Determine the frequency of the absorbed radiation. [1 eV = 1.6 × 10^−19 J, h = 6.6 × 10^−34 Js]",
    "options": ["7.93×10^15Hz", "3.59×10^16Hz", "5.39×10^15Hz", "1.24×10^15Hz"],
    "correctAnswer": "7.59×10^15Hz"
  },
  {
    "id": "26",
    "name":
        "A liquid is left in an open dish. After several days, there is less liquid in the dish. Which of the following statements explains this observation? The",
    "options": [
      "most energetic molecules leave the surface and escape into the air.",
      "least energetic molecules leave the surface and escape into air.",
      "most energetic molecules leave the surface and return.",
      "least energetic molecules leave the surface and return."
    ],
    "correctAnswer":
        "most energetic molecules leave the surface and escape into the air."
  },
  {
    "id": "27",
    "name":
        "The specific latent heat of vaporization of lead is 8.7 × 10^5J/kg. This means that 8.7 × 10^5 J of thermal energy is required to change",
    "options": [
      "a given mass of molten lead to vapor at constant temperature and pressure.",
      "1 kg of molten lead to vapor at constant temperature and pressure.",
      "1 kg of solid lead to vapor at constant temperature and pressure.",
      "1 kg of molten lead to vapor for every degree rise in temperature."
    ],
    "correctAnswer":
        "1 kg of molten lead to vapor at constant temperature and pressure."
  },
  {
    "id": "28",
    "name":
        "The stress experienced by a wire of diameter yπ m loaded by a weight y2 N is",
    "options": ["π Nm−2", "2π Nm−2", "4π Nm−2", "8π Nm−2"],
    "correctAnswer": "4π Nm−2"
  },
  {
    "id": "29",
    "name":
        "A car, P, with a velocity of 30 m/s is traveling in the same direction as a car, Q, with a velocity of 20 m/s. The velocity of P relative to Q is",
    "options": ["50ms1", "45ms1", "20ms1", "10ms1"],
    "correctAnswer": "10ms1"
  },
  {
    "id": "30",
    "name":
        "When a light-weight body and a massive body are acted upon by the same force for the same period of time, the",
    "options": [
      "massive body has a higher momentum.",
      "massive body builds up a higher velocity.",
      "lighter body has a higher momentum.",
      "momenta of both bodies remain the same."
    ],
    "correctAnswer": "massive body has a higher momentum."
  },
  {
    "id": "31",
    "name":
        "A cell of emf 2 V has an internal resistance of 0.5 Ω. A current of 0.4 A passes through an external resistor, P. Determine the resistance of P.",
    "options": ["4.5Ω", "5Ω", "1Ω", "4Ω"],
    "correctAnswer": "4Ω"
  },
  {
    "id": "32",
    "name":
        "A direct current cannot pass through a parallel plate capacitor because",
    "options": [
      "the plates are non-conducting.",
      "the dielectric between the plates is non-conducting.",
      "there is a leakage of charge from the plates.",
      "the plates have equal but opposite charges."
    ],
    "correctAnswer": "the dielectric between the plates is non-conducting."
  },
  {
    "id": "33",
    "name": "The sagging of overhead electrical wires is caused by",
    "options": [
      "radiation of heat.",
      "rough handling.",
      "gravitational attraction",
      "Linear expansion"
    ],
    "correctAnswer": "Linear expansion"
  },
  {
    "id": "34",
    "name":
        "The property of a body that determines the direction of heat flow when the body is in contact with another body is the",
    "options": ["Heat capacity", "mass", "Power", "Temperature"],
    "correctAnswer": "Temperature"
  },
  {
    "id": "35",
    "name":
        "The colours of the visible light region of the electromagnetic spectrum that have the shortest and longest wavelengths respectively are",
    "options": [
      "red and blue.",
      "indigo and violet",
      "violet and red.",
      "yellow and blue."
    ],
    "correctAnswer": "violet and red."
  },
  {
    "id": "36",
    "name":
        "A ball, P, is released from the roof of a building at the same time as another ball, Q, is thrown vertically upward from the base of the building. Which of the following statements is correct?",
    "options": [
      "The acceleration of P is greater than that of Q and both are in the same direction.",
      "The acceleration of P is less than that of Q and both are in the same direction.",
      "The acceleration of P is equal to that of Q and both are in the same direction.",
      "The acceleration of P is equal to that of Q and are in opposite directions."
    ],
    "correctAnswer":
        "The acceleration of P is equal to that of Q and are in opposite directions."
  },
  {
    "id": "37",
    "name":
        "A lead bullet of mass 0.05 kg is fired with a speed of 200 m/s into a lead block of mass 0.95 kg at rest. Given that the lead block moves after the impact, determine its kinetic energy.",
    "options": ["150J", "200J", "50J"],
    "correctAnswer": "50J"
  },
  {
    "id": "38",
    "name":
        "In the Rutherford scattering experiment, a beam of alpha particles was fired at a thin gold film and few of the particles were deflected considerably. This shows that the nucleus of an atom",
    "options": [
      "is positively charged and is concentrated in a tiny volume",
      "contains protons and electrons distributed in a tiny volume.",
      "is concentrated in a tiny volume and contains alpha particles.",
      "is distributed in a tiny volume and emits alpha particles."
    ],
    "correctAnswer":
        "is positively charged and is concentrated in a tiny volume"
  },
  {
    "id": "39",
    "name":
        "What is the name given to the force of attraction between the nucleons in the nucleus of an atom?",
    "options": [
      "Gravitational force.",
      "Electrostatic force.",
      "Magnetic force.",
      "Nuclear force."
    ],
    "correctAnswer": "Nuclear force."
  },
  {
    "id": "40",
    "name": "When an electron jumps directly from an orbit of n = 4 to n = 2,",
    "options": [
      "a photon is absorbed",
      "a photon is emitted",
      "two photons are emitted.",
      "two photons are absorbed"
    ],
    "correctAnswer": "a photon is emitted"
  },
  {
    "id": "41",
    "name":
        "Two objects, A and B, accelerate from rest at uniform rates. B accelerates twice as much as Compared to A, B travels",
    "options": [
      "at the same distance as A",
      "six times as far.",
      "two times as far",
      "three times as far"
    ],
    "correctAnswer": "two times as far"
  },
  {
    "id": "42",
    "name":
        "Which part of the human eye performs the same function as the diaphragm in a lens camera?",
    "options": ["Choroid", "Retina", "Iris", "Cornea"],
    "correctAnswer": "Iris"
  },
  {
    "id": "43",
    "name":
        "Which of the following equations is not a correct mirror formula? [The symbols have their usual meanings]",
    "options": ["N = 360θ", "1f=1u+1v", "m = vu", "f = 1D"],
    "correctAnswer": "N = 360θ"
  },
  {
    "id": "44",
    "name":
        "Which of the following devices is associated with alternating currents only?",
    "options": [
      "Step-up transformer",
      "Induction coil",
      "Moving coil galvanometer",
      "Lead-acid accumulator"
    ],
    "correctAnswer": "Step-up transformer"
  },
  {
    "id": "45",
    "name":
        "The conclusive test for magnetism in a steel bar suspended horizontally at its midpoint is when the bar",
    "options": [
      "always settles in the magnetic N-S direction.",
      "is repelled by a magnet.",
      "always settles in the magnetic E-W direction",
      "is attracted by a magnet."
    ],
    "correctAnswer": "always settles in the magnetic N-S direction."
  },
  {
    "id": "46",
    "name": "The purpose of commutators in a direct current motor is to",
    "options": [
      "reverse the direction of the current after every half rotation",
      "increase the number of rotations per second",
      "enable a uniform couple to act on the coil.",
      "increase the efficiency of the motor."
    ],
    "correctAnswer":
        "reverse the direction of the current after every half rotation"
  },
  {
    "id": "47",
    "name":
        "In which of the following states is MAXIMUM pressure exerted on a person",
    "options": [
      "Standing on two feet",
      "Standing on one foot",
      "Lying on the floor",
      "Kneeling on the floor"
    ],
    "correctAnswer": "Standing on one foot"
  },
  {
    "id": "48",
    "name": "What are cathode rays?",
    "options": [
      "Stream of electrons",
      "Beam of neutrons",
      "Beam of protons",
      "Stream of alpha particles"
    ],
    "correctAnswer": "Stream of electrons"
  },
  {
    "id": "49",
    "name": "The capacitance of a parallel plate capacitor",
    "options": [
      "decreases when the temperature between the plates decreases",
      "increases when the potential difference between the plates is increased",
      "is greater without a dielectric between the plates than with dielectric",
      "is greater with dielectric between the plates than without dielectric."
    ],
    "correctAnswer":
        "is greater with dielectric between the plates than without dielectric."
  },
  {
    "id": "50",
    "name":
        "A ray of light travels from a less dense medium to a denser medium. How are the speed and frequency of the light affected? The speed",
    "options": [
      "Increases and the frequency increases",
      "decreases and the frequency decreases",
      "increases and the frequency remains the same",
      "decreases and the frequency remains the same"
    ],
    "correctAnswer": "decreases and the frequency remains the same"
  },
  {
    "id": "51",
    "name": "Under which conditions is work done",
    "options": [
      "A man supports a heavy load on his head with hands.",
      "A woman holds a pot of water",
      "A boy climbs onto a table",
      "A man pushes against a stationary petrol tanker"
    ],
    "correctAnswer": "A boy climbs onto a table"
  },
  {
    "id": "3",
    "name": "Rainbow is formed when sunlight undergoes",
    "options": ["reflection", "refraction", "dispersion", "diffraction"],
    "correctAnswer": "dispersion"
  },
  {
    "id": "4",
    "name": "Find the value of a capacitor with voltage 5V and 30C.",
    "options": ["7f", "6f", "15f", "0.17f"],
    "correctAnswer": "6f"
  },
  {
    "id": "5",
    "name": "When a bus is accelerating, it must be",
    "options": [
      "changing its speed",
      "changing its velocity",
      "changing its position",
      "changing its direction"
    ],
    "correctAnswer": "changing its velocity"
  },
  {
    "id": "6",
    "name": "The friction due to air mass can be reduced by",
    "options": ["streaming", "lubricating", "propeller", "polishing"],
    "correctAnswer": "streaming"
  },
  {
    "id": "7",
    "name":
        "Which of the following operates based on magnetic effect of electric current?",
    "options": ["electric heater", "photocell", "Dynamo", "Cold cathode"],
    "correctAnswer": "Dynamo"
  },
  {
    "id": "8",
    "name":
        "When a charged ebonite rod is brought near a charged glass rod, there will be",
    "options": ["attraction", "repulsion", "spark", "no force experienced"],
    "correctAnswer": "repulsion"
  },
  {
    "id": "9",
    "name":
        "Pilots uses aneroid barometer to know the height above sea level because",
    "options": [
      "Very accurate",
      "Small and convenient",
      "Heavy and huge",
      "Costly"
    ],
    "correctAnswer": "Small and convenient"
  },
  {
    "id": "10",
    "name":
        "A light ray passing from air into water at an angle of 30º from the normal in air would",
    "options": [
      "make an angle greater than 30º in water surface",
      "be completely absorbed by the water surface",
      "be completely reflected by the water surface",
      "make an angle less than 30º from the normal in water"
    ],
    "correctAnswer": "make an angle less than 30º from the normal in water"
  },
  {
    "id": "11",
    "name":
        "A solid cube of aluminum is 1.5cm on each edge. The density of aluminum is 2700kgm−1. Find the mass of the cube.",
    "options": ["7.5g", "9.1g", "12.0g", "15.0g"],
    "correctAnswer": "9.1g"
  },
  {
    "id": "12",
    "name":
        "5 X 10−3 kg of liquid at its boiling point is evaporated in 20s by the heat generated by a resistor of 2Ω when a current of 10A is used. The specific latent heat of vaporization of the liquid is",
    "options": [
      "8.0 x 104 Jkg−1",
      "8.0 x 105 Jkg−1",
      "8.0 x 106 Jkg−1",
      "8.0 x 107 Jkg−1"
    ],
    "correctAnswer": "8.0 x 105 Jkg−1"
  },
  {
    "id": "13",
    "name":
        "If the S.V.P of water vapour was 13.5mmHg at 33ºC and 7.3mmHg at 7ºC. Find the percentage relative of the air on a day when average air temperature was 33ºC and dew point was 7ºC.",
    "options": ["55%", "60%", "54%", "51%"],
    "correctAnswer": "54%"
  },
  {
    "id": "14",
    "name": "Electrolysis can be investigated using",
    "options": ["Voltmeter", "Ammeter", "Galvanometer", "Voltameter"],
    "correctAnswer": "Voltameter"
  },
  {
    "id": "15",
    "name":
        "A wheelbarrow inclined at 60º to the horizontal is pushed with a force of 150N. What is the horizontal component of the applied force",
    "options": ["130N", "75N", "60N", "50N"],
    "correctAnswer": "75N"
  },
  {
    "id": "16",
    "name": "In a solar panel, solar beam is concentrated by using",
    "options": [
      "Concave mirror",
      "Convex mirror",
      "Plane mirror",
      "Triangular mirror"
    ],
    "correctAnswer": "Concave mirror"
  },
  {
    "id": "17",
    "name": "A rectifier is a device that changes",
    "options": ["D.C to D.C", "D.C to A.C", "A.C to A.C", "A.C to D.C"],
    "correctAnswer": "A.C to D.C"
  },
  {
    "id": "18",
    "name": "The dimension of young's modulus, E is given by",
    "options": ["MLT−1", "MT−2", "ML−1 T−2", "M−1 T"],
    "correctAnswer": "ML−1 T−2"
  },
  {
    "id": "19",
    "name":
        "The moon's acceleration due to gravity is 1/6 of the earth's value. The weight of a bowling ball on the moon would be",
    "options": [
      "6 times its weight on the earth",
      "1/6 of its weight on the earth",
      "36 times its weight on the earth",
      "equal to its weight on the earth"
    ],
    "correctAnswer": "1/6 of its weight on the earth"
  },
  {
    "id": "20",
    "name":
        "If a sheet of an insulating material is inserted between the plates of an air capacitor, the capacitance will",
    "options": ["become zero", "decrease", "increase", "remain unchanged"],
    "correctAnswer": "increase"
  },
  {
    "id": "21",
    "name":
        "288KJ is conducted across two opposite faces of a 3m cube of temperature gradient 90ºCm−1 in 7200s. Calculate the thermal conductivity.",
    "options": [
      "4.9 x 10−2 Wm−1 k−1",
      "5.0 x 10−2 Wm−1 k−1",
      "5.2 x 10−2 Wm−1 k−1",
      "5.1 x 10−2 Wm−1 k−1"
    ],
    "correctAnswer": "5.0 x 10−2 Wm−1 k−1"
  },
  {
    "id": "22",
    "name":
        "A sonometer's fundamental note is 50Hz, what is the new frequency when the tension is four times the original?",
    "options": ["25Hz", "100Hz", "200Hz", "250Hz"],
    "correctAnswer": "100Hz"
  },
  {
    "id": "23",
    "name": "Which of the following is not a part of model rocket?",
    "options": [
      "The body tube",
      "The nose cones",
      "The fin",
      "Not recovery devices"
    ],
    "correctAnswer": "Not recovery devices"
  },
  {
    "id": "24",
    "name":
        "A thick glass tumbler cracks when boiling water is poured into it because",
    "options": [
      "The inside expands more rapidly than the outside",
      "The inside expands less rapidly than the outside",
      "The expansion is even",
      "It does not expand"
    ],
    "correctAnswer": "The inside expands more rapidly than the outside"
  },
  {
    "id": "25",
    "name":
        "How much joules of heat are given out when a piece of iron, of mass 60g and specific heat capacity 460JKg−1 K−1, cools from 75ºC to 35ºC",
    "options": ["1000J", "1050J", "1067J", "1104J"],
    "correctAnswer": "1104J"
  },
  {
    "id": "26",
    "name":
        "The energy of light of frequency 2.0 x 1015 Hz is (h = 6.63 x 10−34 Js)",
    "options": [
      "3.33 x 10−18 J",
      "1.33 x 10−18 J",
      "1.33 x 10−19 J",
      "3.33 x 10−19 J"
    ],
    "correctAnswer": "1.33 x 10−18 J"
  },
  {
    "id": "27",
    "name":
        "A mass of gas at 40mmHg is heated from 298k to 348k at constant volume. Calculate the pressure exerted by the gas.",
    "options": ["50.21mmHg", "46.71mmHg", "42.35mmHg", "35.12mmHg"],
    "correctAnswer": "46.71mmHg"
  },
  {
    "id": "28",
    "name":
        "The distance between two successive crests of a water wave is 0.25m. If a particle on the surface of the water makes four complete vertical oscillations in one second. Calculate the speed of the wave.",
    "options": ["4ms−1", "3ms−1", "2ms−1", "1ms−1"],
    "correctAnswer": "1ms−1"
  },
  {
    "id": "29",
    "name":
        "The thermometer whose thermometric property is change in volume with temperature is",
    "options": [
      "Resistance thermometer",
      "Thermocouple",
      "Bimetallic thermometer",
      "Liquid-in-glass thermometer"
    ],
    "correctAnswer": "Liquid-in-glass thermometer"
  },
  {
    "id": "30",
    "name":
        "In a series resonant circuit, the current flowing in the circuit is",
    "options": ["maximum", "minimum", "zero", "unaffected"],
    "correctAnswer": "maximum"
  },
  {
    "id": "31",
    "name":
        "If a body in linear motion changes from point P to Q, the motion is",
    "options": ["Translational", "Rotational", "Simple harmonic", "Circular"],
    "correctAnswer": "Translational"
  },
  {
    "id": "32",
    "name": "Which of these gas laws is equivalent to workdone",
    "options": [
      "Charle's law",
      "Pressure law",
      "Boyle's law",
      "Gay Lussac's law"
    ],
    "correctAnswer": "Boyle's law"
  },
  {
    "id": "33",
    "name":
        "The process of adding impurities to a semiconductor material to increase its conductivity is",
    "options": ["Rectification", "Emission", "Doping", "Stabilization"],
    "correctAnswer": "Doping"
  },
  {
    "id": "34",
    "name":
        "A load of 300N is to be lifted by a machine with a velocity ratio of 2 and an efficiency of 60%. What effort will be applied to lift the load?",
    "options": ["100N", "150N", "250N", "400N"],
    "correctAnswer": "250N"
  },
  {
    "id": "35",
    "name":
        "The average translational kinetic energy of gas molecules depends on",
    "options": [
      "Temperature only",
      "Number of moles and temperature",
      "Pressure and temperature",
      "Pressure only"
    ],
    "correctAnswer": "Temperature only"
  },
  {
    "id": "36",
    "name":
        "The fourth overtone of a closed pipes is 900Hz, its fundamental frequency is",
    "options": ["50Hz", "100Hz", "200Hz", "400Hz"],
    "correctAnswer": "200Hz"
  },
  {
    "id": "1",
    "name":
        "A particle of charge q and mass m moving with a velocity v enters a uniform magnetic field B in the direction of the field. The force on the particle is",
    "options": ["Bqv", "Bqvm", "Bqvm", "mvBq", "mvBq"],
    "correctAnswer": "Bqv"
  },
  {
    "id": "2",
    "name": "The helium isotope 32He",
    "options": [
      "has three protons and two neutrons",
      "has two protons and one neutron",
      "has two protons and three neutrons",
      "has one proton and two neutrons",
      "cannot exist because it has the same mass number as tritium"
    ],
    "correctAnswer": "has two protons and one neutron"
  },
  {
    "id": "3",
    "name":
        "When a metal is heated to a high temperature, electrons are emitted from its surface. The process is known as",
    "options": [
      "photoelectric effect",
      "thermionic emission",
      "field emission",
      "secondary emission",
      "radioactive emission"
    ],
    "correctAnswer": "thermionic emission"
  },
  {
    "id": "4",
    "name":
        "A piece of stone weights 180 N in air and 150 N in a beaker containing 160 N of methylated spirit. What is the upthrust exerted on the stone?",
    "options": ["50N", "40N", "30N", "20N", "10N"],
    "correctAnswer": "30N"
  },
  {
    "id": "5",
    "name":
        "The half-life of a radioactive substance is 2 seconds. Calculate the decay constant.",
    "options": [
      "2.890 s-1",
      "1.445 s-1",
      "0.576 s-1",
      "0.347 s-1",
      "0.152 s-1"
    ],
    "correctAnswer": "0.347 s-1"
  },
  {
    "id": "6",
    "name":
        "Which of the following is used in a nuclear reactor to slow down fast moving neutrons?",
    "options": [
      "graphite rods",
      "carbon dioxide gas",
      "liquid sodium metal",
      "concrete shield",
      "boron rods"
    ],
    "correctAnswer": "graphite rods"
  },
  {
    "id": "7",
    "name":
        "When electrical power is transmitted over long distances, the voltage is stepped up so that",
    "options": [
      "the resistance of the wire may be increased proportionately to the potential difference",
      "the time of transmissions between the generating and the receiving stations may be reduced",
      "there is increased current to produce brighter lights",
      "the rate of electrical consumption is increased",
      "the energy waste may be minimised as the current is lowered"
    ],
    "correctAnswer":
        "the energy waste may be minimised as the current is lowered"
  },
  {
    "id": "8",
    "name":
        "A gas occupies a certain volume at 27°C. At what temperature will its volume be twice times the original volume assuming that its pressure remains constant?",
    "options": ["54°C", "108°C", "150°C", "327°C", "600°C"],
    "correctAnswer": "327°C"
  },
  {
    "id": "1",
    "name":
        "What is the coefficient of static friction between a load of mass 2kg and a horizontal surface, if the limiting frictional force is 10N? (g = 10 ms-2)",
    "options": ["0.2", "0.5", "2", "5", "8"],
    "correctAnswer": "0.5"
  },
  {
    "id": "2",
    "name":
        "When a lever is in equilibrium, under the action of two or more forces, the algebraic sum of the moments of the forces about the point of support is",
    "options": [
      "anti-clockwise",
      "clockwise",
      "equal to the product to the forces",
      "numerically equal to the total forces acting",
      "equal to zero"
    ],
    "correctAnswer": "equal to zero"
  },
  {
    "id": "3",
    "name":
        "The specific heat of a substance in the solid state is C1; its specific beat in the liquid state is C2 and its latent heat of fusion is L. If a mass M of the substance is changed from the solid state at temperature T, to the liquid state, also at temperature T, the amount of heat required will be",
    "options": [
      "M(C1 ÷ C2) x T",
      "ML",
      "L",
      "M(C1 + C2) × T ÷ ML",
      "ML(C1 + C2 ÷ 2) × T"
    ],
    "correctAnswer": "ML"
  },
  {
    "id": "4",
    "name":
        "An element of nuclear number A and proton number Z emits an alpha particle from its nucleus. The nucleon number and the proton number of the new element formed are respectively",
    "options": [
      "(A – 2) and (Z – 2)",
      "(A + 4) and (Z + 2)",
      "(A– 4) and (Z+2)",
      "(A+ 4) and (Z – 2)",
      "(A – 4) and (Z – 2)"
    ],
    "correctAnswer": "(A – 4) and (Z – 2)"
  },
  {
    "id": "5",
    "name":
        "The force exerted on a charged body in an electric field depends on I. the charge on the body II. the electric field intensity III. the square of the mass of the body",
    "options": [
      "I only",
      "II only",
      "I and II only",
      "I and III only",
      "II and III only"
    ],
    "correctAnswer": "I and II only"
  },
  {
    "id": "6",
    "name":
        "400g of cold water is added to 200g of water at 70°C. If they are properly mixed and the temperature of the mixture is 30°C. calculate the initial temperature of the cold water. (Neglect the heat absorbed by the container)",
    "options": ["10°C", "15°C", "20°C", "30°C", "40°C"],
    "correctAnswer": "20°C"
  },
  {
    "id": "7",
    "name":
        "The heat from a fire in a closed room reaches someone far away in the room, mainly by",
    "options": [
      "reflection",
      "diffusion",
      "conduction",
      "radiation",
      "convection"
    ],
    "correctAnswer": "radiation"
  },
  {
    "id": "8",
    "name":
        "A solid weights 5.0 N in air, 4.2 N in water and 4.4 N in liquid Y. Calculate the relative density of liquid Y.",
    "options": ["0.75", "0.88", "0.95", "1.13", "1.33"],
    "correctAnswer": "0.88"
  },
  {
    "id": "9",
    "name":
        "Two forces forming a couple are separated by a distance of 25cm. If one of the forces equals 40N, what is the moment of the couple?",
    "options": ["1000 Nm", "500 Nm", "10 Nm", "5 Nm", "1.6 Nm"],
    "correctAnswer": "10 Nm"
  },
  {
    "id": "10",
    "name":
        "A radioactive substance has a half-life of 3 minutes. After 9 minutes, the count rate was observed to be 200. What was the count rate at zero time?",
    "options": ["200", "1200", "1600", "2400", "4800"],
    "correctAnswer": "1600"
  }
];
